source 'https://rubygems.org'


gem 'rails', ' ~> 4.2.7'
gem 'pg', '~>0.18.4'
gem 'sass-rails', '~>5.0.4'
gem 'uglifier', '~>2.7.2'
gem 'coffee-rails', '~>4.1.0'
gem 'jquery-rails', '~>4.0.5'
gem 'jbuilder', '~>2.3.2'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem "rspec-rails"
end
