source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', ' ~> 4.2.7'
gem 'pg', '~>0.18.4'
gem 'sass-rails', '~>5.0.4'
gem 'uglifier', '~>2.7.2'
gem 'coffee-rails', '~>4.1.0'
gem 'jquery-rails', '~>4.0.5'
gem 'jbuilder', '~>2.3.2'
gem 'rails_12factor', '~>0.0.3', group: :production
gem 'puma', '~>2.15.3'

group :development, :test do
  gem 'rspec-rails', '~>3.5'
  gem 'poltergeist', '~>1.8.1'
end
